# Copyright (c) Christopher Di Bella.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
task:
  container:
    dockerfile: config/ci/Dockerfile
    cpu: 8
    memory: 16G
  env:
    CLANG_TIDY_PATH: /usr/local/bin/clang-tidy
    matrix:
      - PROFILE: clang-libcxx
    matrix:
      - BUILD_TYPE: Debug
      - BUILD_TYPE: Release

  pre_install_script:
    - mkdir -p build-${BUILD_TYPE}
    - conan config install config/conan
  conan_install_script:
    - cd build-${BUILD_TYPE}
    - conan install ..
        --profile=${PROFILE}
        --settings build_type=${BUILD_TYPE}
        --build
  conan_build_configure_script:
    - cd build-${BUILD_TYPE}
    - conan build .. --configure
  build_script:
    - cd build-${BUILD_TYPE}
    - conan build .. --build
  test_script:
    - cd build-${BUILD_TYPE}
    - conan build .. --test
  install_script:
    - conan create . cirrus/ci --profile=${PROFILE}
