# Copyright (c) Christopher Di Bella.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
task:
  container:
    image: cjdb/cirrus-ci
    cpu: 8
    memory: 8G
  env:
    CLANG_TIDY_PATH: /usr/local/bin/clang-tidy
    matrix:
      - PROFILE: clang-libcxx
        ENABLE_CLANG_TIDY: On
    matrix:
      - BUILD_TYPE: Debug
      - BUILD_TYPE: Release

  pre_install_script:
    - mkdir -p build-${BUILD_TYPE}
    - conan config install config/conan
  conan_install_script:
    - cd build-${BUILD_TYPE}
    - conan install ..
        --profile=${PROFILE}
        --settings build_type=${BUILD_TYPE}
        --options enable_clang_tidy=${ENABLE_CLANG_TIDY}
        --options clang_tidy_path=${CLANG_TIDY_PATH}
        --build
  conan_build_configure_script:
    - cd build-${BUILD_TYPE}
    - conan build .. --configure
  build_script:
    - cd build-${BUILD_TYPE}
    - conan build .. --build
  test_script:
    - cd build-${BUILD_TYPE}
    - conan build .. --test
